### PR TITLE
Check filter expression evaluation error

### PR DESCRIPTION
**Pull request by rldhont**
Before using the filter expression, tests the expression context with atlas and layer scope.

### CODE REVIEW

**Comment by rldhont** [comment]
I think with this fix, we can publish version 3.0.0

**Comment by rldhont** [comment]
@Gustry you can release tomorrow morning

**Comment by rldhont** [comment]
You can release a new version

**Comment by Gustry** [comment]
Doing it right now
Removing your branch ;-)

**Pull request merged**
