### PR TITLE
[Bugfix] Using QgsConfigCache to load project

### LINKED ISSUE #28: Using QgsCacheConfig to load project
To reuse loaded project in QGIS Server use QgsConfigCache.

* PyQGIS API https://qgis.org/pyqgis/master/server/QgsConfigCache.html
* C++ API https://qgis.org/api/classQgsConfigCache.html

### PR DESCRIPTION
**Pull request by rldhont**
Fixed #28

### CODE REVIEW

**Comment by dmarteau** [comment]
Will not work with py-qgis-server because project is not in cache.

**Comment by dmarteau** [comment]
Or more precisely, it will not solve anything because the project will be loaded twice anyway.

**Comment by Gustry** [comment]
@dmarteau But it will still work in another context than py-qgis-server, right?
So this can still be merged ?

Is there something we can do for py-qgis-server?

**Comment by dmarteau** [comment]
@Gustry  It will duplicate project in any context where a QgsProject instance is passed to the "executeRequest method" of QgServer.  

So, no, you do not have any insurance that il will work in  another context than py-qgis-server.

**Comment by dmarteau** [comment]
In all case, it will not be worse as it is now: i.e duplicating the project. Anyway it cannot be solved here because this is a problem that it has to be solved in the QgsProject implementation itself.

**Comment by rldhont** [comment]
The good solution could be to use a service to directly use the project.

For example we can add an ATLAS service with almost 2 requests:
* GetCapabilities
* GetPrint

Use the filter to rewrite parameters:
* SERVICE=WMS&REQUEST=GetCapabilitiesAtlas to SERVICE=ATLAS&REQUEST=GetCapabilities
* SERVICE=WMS&REQUEST=GetPrintAtlas to SERVICE=ATLAS&REQUEST=GetPrint

And update `print_atlas` to directly get the project and do not load it from path.

**Comment by rldhont** [comment]
The PR #30 replaced this to fix the issue about QGIS Server project cache for plugins.

**Pull request closed without merging**
