### PR TITLE
support printing reports.

### PR DESCRIPTION
**Pull request by 3nids**
Some preliminary work to support printing reports.

I am a bit discovering how it works both on plugin and QGIS side.

I guess we will use the same service. Do we make the exp_filter optional? Do we use a new param to determine if we print an atlas or a report?

### CODE REVIEW

**Comment by 3nids** [comment]
the EXP_FILTER needs to be optional for reports.
Which approach do you prefer: 

1) make the EXP_FILTER is any case
2) add a new parameter LAYOUT_TYPE defaulting to `atlas`, which could be set to `report` allowing differenty behavior on the EXP_FILTER.
3) add a new request `GetReport` along with the exising `GetPrint``

My preference goes to 1 or 2.

**Comment by mbernasocchi** [comment]
@3nids can you explain 1?

**Comment by 3nids** [comment]
@mbernasocchi comment updated

**Comment by mbernasocchi** [comment]
ah, thanks, how would an atlas work without EXP_FILTER? if you see a solution than I'd say 1 or 3

**Comment by 3nids** [comment]
@mbernasocchi I have implemented 1) in 6a04db8
mainly this moves the checking of the EXP_FILTER arg away from service.py to core.py.
It sounds like the best / lightest way to me.

**Comment by 3nids** [comment]
@Gustry this should be ready for review

**Comment by Gustry** [comment]
Can you update the readme?

**Comment by 3nids** [comment]
@Gustry done

**Review by Gustry — APPROVED** [review]
Looks good !
Thanks

**Comment by 3nids** [comment]
Thanks!

**Comment by Gustry** [comment]
@3nids Side question, do you have an idea why Travis is not reporting the failure with your PR ? It was red https://travis-ci.org/github/3liz/qgis-atlasprint/builds but GitHub wasn't aware of it.

it happens on many repositories, we do not have feedback anymore since a week.

**Comment by 3nids** [comment]
I don't know. I have experienced many issues with Travis for quite some time. Maybe GitHub is less motivated since workflows exist. I am slowly moving everything from  Travis to GitHub workflows...

**Comment by Gustry** [comment]
Ok, it seems that somehow, 3Liz organization has been kicked out of Travis ... It's back for all our repositories.
FYI

**Pull request merged**
